### ISSUE TITLE
Ajout de la possibilité d'ajuster l'heure de début

### ISSUE THREAD

**Issue by zoiv** [GetLuko/Covid19-French-Auth#11]
Bonjour,

Serait-il envisageable d'ajouter la possibilité de modifier l'heure d'émission de l'attestation générée ? En indiquant le décalage temporel ou directement l'heure souhaitée par exemple ?

**Comment by y4ns0l0** [comment]
See #12

**Comment by tmosmant** [comment]
Again, merci pour la #12 @y4ns0l0 
On ne peut pas modifier la date dans le passé, par contre on peut le faire dans le futur. Est-ce que ça serait utile à quelqu'un ?
