### ISSUE TITLE
Attestation couvre-feu Dec 2020

### ISSUE THREAD

**Issue by OSHeden** [GetLuko/Covid19-French-Auth#15]
Bonjour
Pourriez vous SVP mettre à jour le générateur pour la nouvelle attestation ?
Merci d'avance pour le bel outil !

**Comment by tmosmant** [comment]
Bonjour, je ne vous ai pas répondu mais ça a été fait :)

**Comment by walrus543** [comment]
Alors ça, c'est cool. Je vais m'en resservir du coup, merci.
