### ISSUE TITLE
MAJ attestation

### ISSUE THREAD

**Issue by ghost** [GetLuko/Covid19-French-Auth#17]
Bonjour,

est ce que c’est possible d’avoir la dernière attestation disponible pour le nouveau confinement 
Merci !!

**Comment by tmosmant** [comment]
Hello @aanks0, c'est prévu dès que dispo 😁
![Screenshot_20210320-102326](https://user-images.githubusercontent.com/3709742/111865299-8d95b400-8966-11eb-8e97-b13851201804.jpg)

**Comment by tmosmant** [comment]
À jour :)
