### ISSUE TITLE
BUG - Le générateur ne marche pas

### ISSUE THREAD

**Issue by HRudyPlayZ** [GetLuko/Covid19-French-Auth#18]
Bonjour,
testé sur Chrome, Firefox, Kiwi Browser et Tor Mobile.
Tous sur un Galaxy S8 sous Android 8.0 Oreo.
Aucun d'eux n'a réussi à télécharger le fichier. Kiwi Browser affichait une animation de chargement constante tandis que les autres affichaient que le fichier a été téléchargé sans être téléchargé.
Merci de fixer ce problème afin que je puisse utiliser Luko, et remplacer le générateur officiel, trop limité.

**Comment by tmosmant** [comment]
Hello, pas évident à reproduire sans le lien utilisé.
Ça donne quoi depuis [https://www.luko.eu/fr/page/covid19attestation](https://www.luko.eu/fr/page/covid19attestation) ?

**Comment by HRudyPlayZ** [comment]
Cela semble être corrigé avec Firefox, Chrome et Tor.
Cependant, le générateur bloque toujours avec Kiwi Browser.
J'utilisais justement la version web directement pour mes tests.

**Comment by tmosmant** [comment]
Peut être que Kiwi Browser garde une version en cache ?

**Comment by tmosmant** [comment]
Pas de nouvelle, bonne nouvelle.
