### ISSUE TITLE
download generate pdf in command line

### ISSUE THREAD

**Issue by bartounet16** [GetLuko/Covid19-French-Auth#2]
I am trying to download the pdf with the generated url

but I can't do it.

How to download pdf with wget or curl from url?

**Comment by bbourdel** [comment]
Hi, 
Hard to make it working with data privacy.
This tool is using your own browser to compile the PDF. So all your personnal info stay on your browser -> nothing is sent to the server.

**Comment by Bbillyben** [comment]
> Hard to make it working with data privacy.

Hi bbourdel,
I just want to add my vote to that enhancement.

I host my own webserver with your attestation generator (many thanks by the way!!!), so not much worried about my data privacy
and that would be very convenient to be able to automatically save the pdf file generated so I can send it directly to my phone.

**Comment by zesk06** [comment]
> > Hard to make it working with data privacy.
> 
> Hi bbourdel,
> I just want to add my vote to that enhancement.
> 
> I host my own webserver with your attestation generator (many thanks by the way!!!), so not much worried about my data privacy
> and that would be very convenient to be able to automatically save the pdf file generated so I can send it directly to my phone.

Hi Bbilyben,
The PDF is saved by the chrome browser on your phone.
What is exactly are you trying to do?
You want to launch a CLI command on a computer, and send the file to your phone using mail?

We could use selenium to automate the download process

**Comment by Bbillyben** [comment]
Hi zesk,
That something like this!
I'm trying to automate the sending of pdf file to my phone, bypassing the browser step to be available on the go (aka in front of the police officer, in no connection area!).

Actually, all automation would be handle by my home automation system (jeedom - which has a webserver by the way).
I didn't know selenium, it sounds promising

**Comment by tmosmant** [comment]
Hi @bartounet16, @Bbillyben,
If that's still something you want to do, I invite you to look at how to do this with Selenium.
A simple example I've participated to [here](https://github.com/chlmchl/twitter-diary/tree/main/src/back) : how to fetch a webpage and behave like a browser to interpret its javascript, accessible from an endpoint.
Have fun!
