### ISSUE TITLE
Not working on my webserver

### ISSUE THREAD

**Issue by rid3r45** [GetLuko/Covid19-French-Auth#3]
Hey,

I just hosted the project on my webserver at the address: https://hardgamer.alwaysdata.net/generate.html.
However it does not create the pdf when I call it with the appropriate parameters. Any idea why that could be and what steps I could follow to solve this issue?
Sincerely

**Comment by bbourdel** [comment]
Hello,
I can't reproduce bug.,
I have a 404.
Sorry
