### ISSUE TITLE
Update to match the new version

### ISSUE THREAD

**Issue by tchlyah** [GetLuko/Covid19-French-Auth#4]
Hello !

You did a great work here. Are you planning to update it for the new version? https://media.interieur.gouv.fr/attestation-couvre-feu-covid-19/

It is very useful for Siri shortcuts!

**Comment by bbourdel** [comment]
Hello !
Hop ! It's done.

You can setup a new Link on : https://www.luko.eu/fr/page/covid19attestation
Best !

**Comment by tchlyah** [comment]
Are you sure? It doesn't work for me, the page keeps loading with no output

**Comment by bbourdel** [comment]
On my side, it seems to work pretty well.
Browser ? Version ? anything on the Console ?

**Comment by tchlyah** [comment]
Today it is working fine! Weird...
