### ISSUE TITLE
Mettre à jour le générateur d'attestation avec les nouveaux cas

### ISSUE THREAD

**Issue by bartounet16** [GetLuko/Covid19-French-Auth#5]
Bonjour.
Pouvez vous mettre à jour le code de l'attestation afin d'intégrer les nouveaux cas possibles de déplacements ? ( sortie scolaire ..)

**Comment by bbourdel** [comment]
C'est en cours :+1:

**Comment by olivgat** [comment]
@bbourdel  je viens juste de mettre à jour le code de mon côté. Je peux te pousser la PR si tu veux :)

**Comment by bbourdel** [comment]
Je viens de le mettre à jour.

**Comment by bbourdel** [comment]
Dispo sur https://www.luko.eu/fr/page/covid19attestation

**Comment by bartounet16** [comment]
Merci les gars c'est super !
