### ISSUE TITLE
Probleme de telechargement

### ISSUE THREAD

**Issue by gmergoux** [GetLuko/Covid19-French-Auth#6]
Bonjour,
A priori pas possible de générer les attestation a 12H30 ce jour (fonctionnait dans la matinée)

**Comment by bbourdel** [comment]
Merci @gmergoux. Problème résolu suite à la MàJ du site gouvernemental

**Comment by gmergoux** [comment]
Merci, je confirme, ca fonctionne!

**Comment by gmergoux** [comment]
Super boulot en tous cas!
