### ISSUE TITLE
autoclose "processing" window

### ISSUE THREAD

**Issue by licks0re** [GetLuko/Covid19-French-Auth#9]
Hello,

A la fin de la génération, une fenetre reste ouverte avec un petit rond qui tourne à l'infini.
Est ce qu'il y a moyen de fermer celle-ci automatiquement ?

Avec un window.close au bout de 5 secondes par exemple, ou un timeout ?

**Comment by gmergoux** [comment]
Même requête 👍

**Comment by zesk06** [comment]
L'autoclose est en place, le problème c'est qu'on a plus le temps de bookmaker le lien.
Peut on mettre à la place de l'auto close, un bouton "fermer cet onglet" qui s'active a la fin de la génération ?

**Comment by tmosmant** [comment]
+1 @zesk06, c'était pas terrible cet autoclose, on a revert et ajouté un bouton.
